### ISSUE TITLE
Failed to activate the linter-ocaml package

### ISSUE THREAD

**Issue by bmwilly** [eriklovlie/automatic-octo-computing-machine#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-ocaml](https://github.com/eriklovlie/automatic-octo-computing-machine) package, v1.1.0
### Stack Trace

Failed to activate the linter-ocaml package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at Object.module.exports.AtomMerlinOcaml.isOcamlEditor (/Users/brandon/.atom/packages/linter-ocaml/lib/atom-merlin-ocaml.coffee:50:14)
    at /Users/brandon/.atom/packages/linter-ocaml/lib/atom-merlin-ocaml.coffee:38:11
    at Workspace.module.exports.Workspace.observeTextEditors (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/workspace.js:302:9)
    at Object.module.exports.AtomMerlinOcaml.activate (/Users/brandon/.atom/packages/linter-ocaml/lib/atom-merlin-ocaml.coffee:37:39)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-ini, v1.16.0
language-markdown, v0.12.0
language-ocaml, v1.1.2
language-r, v0.4.0
linter, v1.11.4
linter-ocaml, v1.1.0
python-indent, v0.4.3
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by eriklovlie** [comment]
Thanks for the bug report. This must mean that `editor.getPath()` returns undefined... do you have any more info on steps to repro? The `TextEditor` api documentation doesn't state that it can return undefined, but I suppose if you have opened a new file it would have to (and anyway this function of mine is lacking in defensive programming).

I will try to do a fix today.

**Comment by eriklovlie** [comment]
Argh... nevermind about the repro case, I see this error also now :) Will fix asap zulu.

**Comment by bmwilly** [comment]
Thanks!

**Comment by eriklovlie** [comment]
Pushed v1.1.1 with this fix. The activation logic needs some more fixes but this patch at least fixes this particular issue (in my testing).

**Comment by bmwilly** [comment]
works for me, thanks
